### ISSUE TITLE
PROBLEMA DBCONNECTION

### ISSUE THREAD

**Issue by donatocatalano** [donatocatalano/centrosportivo#29]
Dopo la tua modifica mi restituisce questo errore e l'app non si avvia:

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at it.unisalento.pps.DbInterface.DbConnection.connetti(DbConnection.java:33)
	at it.unisalento.pps.DbInterface.DbConnection.getInstance(DbConnection.java:22)
	at it.unisalento.pps.dao.DisciplinaDAO.getDiscipline(DisciplinaDAO.java:44)
	at it.unisalento.pps.business.DisciplinaBusiness.getDiscipline(DisciplinaBusiness.java:29)
	at it.unisalento.pps.view.Homepage.<init>(Homepage.java:95)
	at it.unisalento.pps.view.StartApp.main(StartApp.java:6)
java.lang.NullPointerException
	at it.unisalento.pps.DbInterface.DbConnection.eseguiQuery(DbConnection.java:52)
	at it.unisalento.pps.dao.DisciplinaDAO.getDiscipline(DisciplinaDAO.java:44)
	at it.unisalento.pps.business.DisciplinaBusiness.getDiscipline(DisciplinaBusiness.java:29)
	at it.unisalento.pps.view.Homepage.<init>(Homepage.java:95)
	at it.unisalento.pps.view.StartApp.main(StartApp.java:6)
Exception in thread "main" java.lang.NullPointerException
	at it.unisalento.pps.dao.DisciplinaDAO.getDiscipline(DisciplinaDAO.java:49)
	at it.unisalento.pps.business.DisciplinaBusiness.getDiscipline(DisciplinaBusiness.java:29)
	at it.unisalento.pps.view.Homepage.<init>(Homepage.java:95)
	at it.unisalento.pps.view.StartApp.main(StartApp.java:6)

**Comment by giovannidefilippi** [comment]
l'ho rimesso a posto ..riprova chiudo

**Comment by donatocatalano** [comment]
no non  va...a te funziona?

java.lang.ClassNotFoundException: com.mysql.jdbc.Driver
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at it.unisalento.pps.DbInterface.DbConnection.connetti(DbConnection.java:33)
	at it.unisalento.pps.DbInterface.DbConnection.getInstance(DbConnection.java:22)
	at it.unisalento.pps.dao.DisciplinaDAO.getDiscipline(DisciplinaDAO.java:44)
	at it.unisalento.pps.business.DisciplinaBusiness.getDiscipline(DisciplinaBusiness.java:29)
	at it.unisalento.pps.view.Homepage.<init>(Homepage.java:95)
	at it.unisalento.pps.view.StartApp.main(StartApp.java:6)
java.lang.NullPointerException
	at it.unisalento.pps.DbInterface.DbConnection.eseguiQuery(DbConnection.java:52)
	at it.unisalento.pps.dao.DisciplinaDAO.getDiscipline(DisciplinaDAO.java:44)
	at it.unisalento.pps.business.DisciplinaBusiness.getDiscipline(DisciplinaBusiness.java:29)
	at it.unisalento.pps.view.Homepage.<init>(Homepage.java:95)
	at it.unisalento.pps.view.StartApp.main(StartApp.java:6)
Exception in thread "main" java.lang.NullPointerException
	at it.unisalento.pps.dao.DisciplinaDAO.getDiscipline(DisciplinaDAO.java:49)
	at it.unisalento.pps.business.DisciplinaBusiness.getDiscipline(DisciplinaBusiness.java:29)
	at it.unisalento.pps.view.Homepage.<init>(Homepage.java:95)
	at it.unisalento.pps.view.StartApp.main(StartApp.java:6)

**Comment by donatocatalano** [comment]
ok si era mangiato il connector...ora si apre di nuovo...chiudo
